apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: neo4j
type: Opaque
data:
  # Base64 encoded: neo4j/your-secure-password-123
  NEO4J_AUTH: bmVvNGoveW91ci1zZWN1cmUtcGFzc3dvcmQtMTIz